# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: prod
debug: '0'
secret: ChangeMe
corsAllowOrigin: '*'

php:
  repository: eu.gcr.io/api-platform-demo-210115/php
  tag: latest
  pullPolicy: Always
  replicaCount: 1

nginx:
  repository: eu.gcr.io/api-platform-demo-210115/nginx
  tag: latest
  pullPolicy: Always
  replicaCount: 1

varnish:
  enabled: true
  #url: https://example.com
  repository: eu.gcr.io/api-platform-demo-210115/varnish
  tag: latest
  pullPolicy: Always
  replicaCount: 1

ingress:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-platform-demo-ip
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

postgresql:
  enabled: true
  # If bringing your own PostgreSQL, the full uri to use
  #url: pgsql://api-platform:!ChangeMe!@example.com/api?serverVersion=10.1
  postgresUser: api-platform
  postgresPassword: ChangeMe
  postgresDatabase: api
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
