apiVersion: v1
kind: Service
metadata:
  name: api-platform-demo-ip
  labels:
    app: {{ template "name" . }}-ip
spec:
  type: NodePort
  selector:
    app: {{ template "name" . }}
    tier: web
  ports:
  - port: 80
    targetPort: 8080
