version: '3.4'

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: zero_dechet_php
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - db
      - mailcatcher
      - redis
    env_file:
      - ./api/.env

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      target: zero_dechet_nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - php

  redis:
    image: redis:4-alpine

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ./api
      target: zero_dechet_varnish
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - api
    tmpfs:
      - /usr/local/var/varnish:exec

  db:
    image: mdillon/postgis:11-alpine
    healthcheck:
      test: /usr/local/bin/healthcheck
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=zero-dechet
      - POSTGRES_PASSWORD=z3r0d3ch3t

  client:
    image: ${CONTAINER_REGISTRY_BASE}/client
    build:
      context: ./client
      target: zero_dechet_client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    env_file:
      - ./client/.env

  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: ./app
      target: zero_dechet_app
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/app
    env_file:
      - ./app/.env

  admin:
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ./admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/admin
    env_file:
      - ./admin/.env

  h2-proxy:
    build:
      context: ./h2-proxy
    depends_on:
      - client
      - admin
      - api
      - cache-proxy

  mailcatcher:
    image: tophfr/mailcatcher:0.6.5
