version: '3.4'

services:
  php:
    image: zero-dechet/php
    build:
      context: ./api
      target: zero_dechet_php
      cache_from:
        - zero-dechet/php
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - $HOME/.composer/cache:/root/.composer/cache
      - ./api:/srv/api:rw,cached
      - /srv/api/var/cache/
      - /srv/api/var/log/

  api:
    image: zero-dechet/nginx
    build:
      context: ./api
      target: zero_dechet_nginx
      cache_from:
        - zero-dechet/nginx
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro

  cache-proxy:
    image: zero-dechet/varnish
    build:
      context: ./api
      target: zero_dechet_varnish
      cache_from:
        - zero-dechet/varnish
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec

  db:
    image: mdillon/postgis:11-alpine
    healthcheck:
      test: /usr/local/bin/healthcheck
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=zero-dechet
      - POSTGRES_PASSWORD=z3r0d3ch3t
    volumes:
      - ./api/docker/postgres/healthcheck:/usr/local/bin/healthcheck:rw
      - db-data:/var/lib/postgresql/data:rw

  client:
    image: zero-dechet/client
    build:
      context: ./client
      cache_from:
        - zero-dechet/client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules

  admin:
    image: zero-dechet/admin
    build:
      context: ./admin
      cache_from:
        - zero-dechet/admin
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules

  h2-proxy:
    build:
      context: ./h2-proxy
    depends_on:
      - client
      - admin
      - api
      - cache-proxy

  selenium:
    image: selenium/standalone-chrome:3.14

  mailcatcher:
    image: tophfr/mailcatcher:0.6.5

volumes:
  db-data: {}
