version: '3.4'

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: zero_dechet_php
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
    depends_on:
      - db
      - mailcatcher
      - redis
    env_file:
      - ./api/.env

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      target: zero_dechet_nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
    depends_on:
      - php

  db:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=zero-dechet
      - POSTGRES_PASSWORD=z3r0d3ch3t

  redis:
    image: redis:4-alpine

  mailcatcher:
    image: tophfr/mailcatcher:0.6.5

  app:
    image: ${CONTAINER_REGISTRY_BASE}/app
    build:
      context: ./app
      target: zero_dechet_app
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/app
    env_file:
      - ./app/.env

  admin:
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ./admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/admin
    env_file:
      - ./admin/.env

  h2-proxy:
    build:
      context: ./h2-proxy
    depends_on:
      - admin
      - api
