parameters:
    env(APP_VERSION): '%env(APP_ENV)%'

api_platform:
    title: Zero Déchet
    version: '%env(APP_VERSION)%'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        csv: ['text/csv']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Doctrine\ORM\Extension\SecurityExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Serializer\ContextBuilder:
        decorates: api_platform.serializer.context_builder
        arguments:
            $decorated: '@App\Serializer\ContextBuilder.inner'

    App\Serializer\DocumentationNormalizer:
        decorates: api_platform.swagger.normalizer.documentation
        arguments:
            $decorated: '@App\Serializer\DocumentationNormalizer.inner'
        autoconfigure: false
