parameters:
    env(APP_VERSION): '%env(APP_ENV)%'

api_platform:
    title: Zero Déchet
    version: '%env(APP_VERSION)%'
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
        ics: ['text/calendar']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Doctrine\ORM\Extension\PublishableExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    App\Doctrine\ORM\Extension\EventExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Doctrine\ORM\Extension\RegistrationExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Doctrine\ORM\Extension\NewsletterExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    App\Doctrine\ORM\Extension\SecurityExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Doctrine\ORM\Extension\UserExtension:
        autoconfigure: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }

    App\Serializer\ContextBuilder:
        decorates: api_platform.serializer.context_builder
        arguments:
            $decorated: '@App\Serializer\ContextBuilder.inner'

    api_platform.security.expression_language:
        class: App\Security\ExpressionLanguage

    App\Serializer\DocumentationNormalizer:
        decorates: api_platform.swagger.normalizer.documentation
        arguments:
            $decorated: '@App\Serializer\DocumentationNormalizer.inner'
        autoconfigure: false
