parameters:
    env(MAILER_URL): 'null://localhost'

swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

services:
    Finesse\SwiftMailerDefaultsPlugin\SwiftMailerDefaultsPlugin:
        tags: ['swiftmailer.default.plugin']
        arguments:
            $defaults:
                from:
                    no-reply@zero-dechet.app: Zéro Déchet
