services:
    test.coop_tilleuls_forgot_password.manager.password_token:
        parent: coop_tilleuls_forgot_password.manager.password_token
        public: true

    App\EntityListener\EventEntityListener:
        autowire: true
        autoconfigure: true
        tags: ['doctrine.orm.entity_listener']
        arguments:
            $autoValidateEvents: false
